'use strict';
(() => {
 const root=document.getElementById('achievement-map');if(!root)return;
 const PAGE_SIZE=10; // Public list contract: ten records per page.
 const data=JSON.parse(document.getElementById('map-data').textContent);
 const search=document.getElementById('case-search'),village=document.getElementById('village-filter'),category=document.getElementById('category-filter'),subcategory=document.getElementById('subcategory-filter'),status=document.getElementById('status-filter');
 const list=document.getElementById('case-list'),cards=[...document.querySelectorAll('#case-list [data-case]')],count=document.getElementById('case-count'),empty=document.getElementById('case-empty'),message=document.getElementById('map-message');
 const resetButton=document.getElementById('reset-map-filters'),searchControl=search.closest('div');list.dataset.pageSize=String(PAGE_SIZE);
 const pagination=document.createElement('nav');pagination.className='case-pagination';pagination.setAttribute('aria-label','建設與服務紀錄分頁');pagination.dataset.pageSize=String(PAGE_SIZE);list.after(pagination);
 const searchToggle=document.createElement('button');searchToggle.type='button';searchToggle.id='toggle-map-search';searchToggle.className='map-search-toggle';searchToggle.textContent='搜尋';searchToggle.setAttribute('aria-controls',search.id);resetButton.after(searchToggle);
 let map,markers,boundaries,visible=data,currentPage=1,initial=true;const layers=new Map();
 const initialParams=new URLSearchParams(location.search);
 function setOption(select,value){if([...select.options].some(o=>o.value===value))select.value=value;}
 search.value=initialParams.get('q')||'';setOption(village,initialParams.get('village')||'all');setOption(category,initialParams.get('category')||'all');setOption(subcategory,initialParams.get('subcategory')||'all');setOption(status,initialParams.get('status')||'all');
 function setSearchOpen(open,focus=false){searchControl.hidden=!open;searchToggle.setAttribute('aria-expanded',String(open));searchToggle.classList.toggle('is-active',open);if(open&&focus)search.focus();}
 setSearchOpen(true);
 function fits(c){const q=search.value.trim().toLocaleLowerCase();return (!q||[c.title,c.summary,...c.categories,...(c.subcategories||[]),...c.villages,c.scope].join(' ').toLocaleLowerCase().includes(q))&&(category.value==='all'||c.categories.includes(category.value))&&(subcategory.value==='all'||(c.subcategories||[]).includes(subcategory.value))&&(status.value==='all'||c.status===status.value)&&(village.value==='all'||(village.value==='unassigned'?!c.villages.length&&!['全市政策','跨區服務'].includes(c.scope):village.value.startsWith('v:')?c.villages.includes(village.value.slice(2)):c.scope===village.value.slice(2)));}
 function fit(){if(!map)return;if(village.value.startsWith('v:')&&layers.has(village.value.slice(2))){map.fitBounds(layers.get(village.value.slice(2)).getBounds(),{padding:[24,24],maxZoom:15,animate:false});return;}const pts=visible.filter(x=>x.coordinates).map(x=>x.coordinates);if(pts.length)map.fitBounds(L.latLngBounds(pts),{padding:[35,35],maxZoom:15,animate:false});else if(boundaries)map.fitBounds(boundaries.getBounds(),{padding:[15,15],animate:false});}
 function makePageButton(text,page,{current=false,disabled=false,label=''}={}){const button=document.createElement('button');button.type='button';button.className='case-page-button';button.textContent=text;button.disabled=disabled;if(current)button.setAttribute('aria-current','page');button.setAttribute('aria-label',label||`第 ${page} 頁`);button.addEventListener('click',()=>{currentPage=page;renderCards();document.getElementById('case-results').scrollIntoView({behavior:'smooth',block:'start'});});return button;}
 function renderPagination(){pagination.replaceChildren();const totalPages=Math.max(1,Math.ceil(visible.length/PAGE_SIZE));currentPage=Math.min(Math.max(1,currentPage),totalPages);if(visible.length<=PAGE_SIZE){pagination.hidden=true;return;}pagination.hidden=false;pagination.append(makePageButton('上一頁',Math.max(1,currentPage-1),{disabled:currentPage===1,label:'上一頁'}));for(let page=1;page<=totalPages;page+=1)pagination.append(makePageButton(String(page),page,{current:page===currentPage}));pagination.append(makePageButton('下一頁',Math.min(totalPages,currentPage+1),{disabled:currentPage===totalPages,label:'下一頁'}));}
 function renderCards(){const totalPages=Math.max(1,Math.ceil(visible.length/PAGE_SIZE));currentPage=Math.min(Math.max(1,currentPage),totalPages);const start=(currentPage-1)*PAGE_SIZE,pageIds=new Set(visible.slice(start,start+PAGE_SIZE).map(c=>c.id));cards.forEach(card=>card.hidden=!pageIds.has(card.dataset.case));const mapped=visible.filter(c=>c.coordinates).length;count.textContent=visible.length?`共 ${visible.length} 個專題 · 第 ${currentPage}/${totalPages} 頁 · ${mapped} 個有點位紀錄`:'共 0 個專題';empty.hidden=visible.length>0;renderPagination();}
 function showCaseCard(id){const index=visible.findIndex(c=>c.id===id);if(index<0)return;currentPage=Math.floor(index/PAGE_SIZE)+1;renderCards();document.querySelectorAll('.case-card.is-selected').forEach(e=>e.classList.remove('is-selected'));document.querySelector(`[data-case="${id}"]`)?.classList.add('is-selected');}
 function draw(){if(!map)return;markers.clearLayers();const groups=new Map();visible.filter(c=>c.coordinates).forEach(c=>{const k=c.coordinates.join(',');if(!groups.has(k))groups.set(k,[]);groups.get(k).push(c);});for(const cases of groups.values()){
   const pop=document.createElement('div');pop.className='map-popup';const title=document.createElement('strong');title.textContent=cases.length>1?`${cases.length} 個相關專題`:cases[0].title;pop.append(title);
   cases.forEach(c=>{const a=document.createElement('a');a.href=`achievement-${c.id}.html`;a.textContent=c.title+' →';pop.append(a);});
   const marker=L.marker(cases[0].coordinates,{icon:L.divIcon({className:'case-marker',html:`<span>${cases.length}</span>`,iconSize:[34,34],iconAnchor:[17,17]}),title:cases.map(c=>c.title).join('、'),keyboard:true}).bindPopup(pop,{maxWidth:320,autoPan:false});marker.addTo(markers);marker.on('click',()=>showCaseCard(cases[0].id));
 }
 if(boundaries)boundaries.setStyle(f=>({color:village.value==='v:'+f.properties.name?'#c36a32':'#4b7464',weight:village.value==='v:'+f.properties.name?3:1,fillColor:village.value==='v:'+f.properties.name?'#def68d':'#8faf9a',fillOpacity:village.value==='v:'+f.properties.name?.45:.08}));}
 function syncURL(){const p=new URLSearchParams();if(search.value.trim())p.set('q',search.value.trim());if(village.value!=='all')p.set('village',village.value);if(category.value!=='all')p.set('category',category.value);if(subcategory.value!=='all')p.set('subcategory',subcategory.value);if(status.value!=='all')p.set('status',status.value);history.replaceState(null,'',location.pathname+(p.size?'?'+p.toString():''));}
 function filter(update=true,resetPage=true){if(resetPage)currentPage=1;visible=data.filter(fits);renderCards();draw();if(update){syncURL();fit();}}
 function reset(){search.value='';village.value=category.value=subcategory.value=status.value='all';setSearchOpen(true);filter();}
 searchToggle.addEventListener('click',()=>setSearchOpen(true,true));
 search.addEventListener('input',()=>filter());[village,category,subcategory,status].forEach(e=>e.addEventListener('change',()=>filter()));resetButton.addEventListener('click',reset);document.querySelector('[data-clear-filters]')?.addEventListener('click',reset);document.getElementById('map-fit').addEventListener('click',fit);
 document.querySelectorAll('[data-locate]').forEach(button=>button.addEventListener('click',()=>{const c=data.find(x=>x.id===button.dataset.locate);if(!map||!c?.coordinates){message.textContent='地圖目前無法使用，請直接閱讀專題詳情。';return;}showCaseCard(c.id);map.setView(c.coordinates,16,{animate:false});markers.eachLayer(marker=>{const p=marker.getLatLng();if(p.lat===c.coordinates[0]&&p.lng===c.coordinates[1])marker.openPopup();});root.scrollIntoView({behavior:'smooth',block:'center'});}));
 filter(false,false);
 if(!window.L){message.textContent='互動地圖暫時無法載入，篩選與完整紀錄仍可使用。';root.querySelector('.map-startup').textContent='請由列表閱讀完整紀錄。';return;}
 root.replaceChildren();map=L.map(root,{scrollWheelZoom:false,zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false}).setView([22.615,120.351],13);markers=L.layerGroup().addTo(map);
 let tileErrors=0;const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
 tiles.on('tileerror',()=>{tileErrors++;if(tileErrors>=3)message.textContent='部分底圖未能載入；里界、點位及完整紀錄仍可使用。';});
 const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);
 fetch('assets/fengshan-villages.geojson',{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error('boundaries');return r.json();}).then(geo=>{boundaries=L.geoJSON(geo,{onEachFeature:(f,layer)=>{layers.set(f.properties.name,layer);layer.bindTooltip(f.properties.name);const choose=()=>{village.value='v:'+f.properties.name;filter();};layer.on('click',choose);layer.on('add',()=>{const el=layer.getElement();if(el){el.setAttribute('role','button');el.setAttribute('aria-label','篩選'+f.properties.name);el.setAttribute('tabindex','0');el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}});}});}}).addTo(map);draw();if(initial){fit();initial=false;}}).catch(()=>{message.textContent='里界圖暫時無法載入，可用里別選單與專題點位查詢。';}).finally(()=>clearTimeout(timeout));
 draw();fit();const requested=data.find(c=>c.id===initialParams.get('case'));if(requested){search.value=requested.title;setSearchOpen(true);village.value=category.value=subcategory.value=status.value='all';filter(false);fit();if(requested.coordinates)markers.eachLayer(marker=>{const p=marker.getLatLng();if(p.lat===requested.coordinates[0]&&p.lng===requested.coordinates[1])marker.openPopup();});}
})();
